# Generated by Django 3.2.3 on 2021-05-31 18:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hiredigital_ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 31, 18, 3, 15, 65874), verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 5, 31, 18, 3, 15, 65903), verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=256, verbose_name='Image Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 31, 18, 3, 15, 65874), verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 5, 31, 18, 3, 15, 65903), verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=256, verbose_name='Category Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='following',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 18, 3, 15, 65874), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='following',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 18, 3, 15, 65903), verbose_name='Updated At'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 31, 18, 3, 15, 65874), verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 5, 31, 18, 3, 15, 65903), verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=256, verbose_name='Product Name')),
                ('stock', models.IntegerField(default=0, verbose_name='Product Stock')),
                ('unit_price', models.PositiveIntegerField(blank=True, verbose_name='Unit Price')),
                ('sale_price', models.PositiveIntegerField(blank=True, verbose_name='Sale Price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='hiredigital_ecom.categories')),
                ('images', models.ManyToManyField(blank=True, related_name='images', to='hiredigital_ecom.Assets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
