# Generated by Django 3.2.3 on 2021-05-31 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiredigital_ecom', '0004_auto_20210531_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 9, 56, 185294), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 9, 56, 185314), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 9, 56, 185294), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 9, 56, 185314), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='following',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 9, 56, 185294), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='following',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 9, 56, 185314), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 9, 56, 185294), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sale_price',
            field=models.FloatField(blank=True, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit_price',
            field=models.FloatField(blank=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 9, 56, 185314), verbose_name='Updated At'),
        ),
    ]
