# Generated by Django 3.2.3 on 2021-05-31 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiredigital_ecom', '0005_auto_20210531_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Product Id'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 20, 2, 486026), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 20, 2, 486047), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 20, 2, 486026), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 20, 2, 486047), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='following',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 20, 2, 486026), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='following',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 20, 2, 486047), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 20, 2, 486026), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 20, 2, 486047), verbose_name='Updated At'),
        ),
    ]
