# Generated by Django 3.2.3 on 2021-05-31 20:31

import datetime
from django.db import migrations, models
import hiredigital_ecom.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('hiredigital_ecom', '0007_auto_20210531_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to=hiredigital_ecom.models.product, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 31, 35, 428425), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 31, 35, 428447), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='following',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 31, 35, 428425), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='following',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 31, 35, 428447), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 31, 35, 428425), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 31, 35, 428447), verbose_name='Updated At'),
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
    ]
