# Generated by Django 3.2.3 on 2021-06-01 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiredigital_ecom', '0014_auto_20210601_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 10, 29, 21, 421213), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 10, 29, 21, 421233), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='following',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 10, 29, 21, 421213), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='following',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 10, 29, 21, 421233), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 10, 29, 21, 421213), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 10, 29, 21, 421233), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='productviewed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 10, 29, 21, 421213), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='productviewed',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 10, 29, 21, 421233), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 10, 29, 21, 421213), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 10, 29, 21, 421233), verbose_name='Updated At'),
        ),
    ]
