# Generated by Django 3.2.3 on 2021-06-01 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiredigital_ecom', '0015_auto_20210601_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 18, 2, 47, 683653), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 18, 2, 47, 683671), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='following',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 18, 2, 47, 683653), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='following',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 18, 2, 47, 683671), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 18, 2, 47, 683653), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 18, 2, 47, 683671), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='productviewed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 18, 2, 47, 683653), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='productviewed',
            name='products_viewed',
            field=models.ManyToManyField(blank=True, related_name='products_viewed', to='hiredigital_ecom.Products'),
        ),
        migrations.AlterField(
            model_name='productviewed',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 18, 2, 47, 683671), verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 18, 2, 47, 683653), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 18, 2, 47, 683671), verbose_name='Updated At'),
        ),
    ]
